# Removing old redis state store
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: test-dapr-state-store
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: "redis:6379"
    - name: actorStateStore
      value: "true"
    - name: ttlInSeconds
      value: "3600" # 1 hour
